# Generated by Django 2.1.5 on 2019-01-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190121_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='default_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=100),
        ),
    ]
