# Generated by Django 2.1.5 on 2019-01-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20190122_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='profitability',
            field=models.CharField(choices=[('Optimum', 'Optimum'), ('Good', 'Good'), ('Bad', 'Bad')], default=2, max_length=7),
        ),
    ]
