# Generated by Django 2.1.5 on 2019-01-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_profitability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='profitability',
            field=models.CharField(choices=[('Optimum', 'Optimum'), ('Good', 'Good'), ('Bad', 'Bad')], default='Good', max_length=7),
        ),
    ]
